### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by juliusbundalian** [Valeriaaan/CanorecoSystem#1]
### **Sunday 11, 2024 ToDo Tasks**  @Valeriaaan 

- [x] Edit Business Center UI & Functions

- [x] Edit Business Center Functions
--------------------------------------------------------------------------------
- [x] Bayad Center UI

- [x] Bayad Center Functions
--------------------------------------------------------------------------------
- [x] Add Bayad Center UI

- [x] Add Bayad Center Functions
